---
- name: "检查目标服务器{{ server_name }}的MySQL是否安装"
  shell: rpm -qa | grep "{{ mysql_package }}" | wc -l  warn=False
  register: yum_result
  ignore_errors: True

- name: "目标服务器{{ server_name }}的MySQL未安装"
  fail: 
    msg: "目标服务器MySQL未安装,请安装之后再进行初始化"
  when: yum_result.stdout == "0"

- name: "检查目标服务器{{ server_name }}的MySQL是否启动"
  shell: ps -ef | grep -v "grep" | grep "{{ mysql_bin }}" | wc -l
  register: ps_result

- name: "目标服务器{{ server_name }}的MySQL未启动"
  fail:
    msg: "目标服务器MySQL未启动,请启动之后再进行初始化"
  when: ps_result.stdout == "0"