---
- name: 检查Jenkins的参数项正确性
  include_tasks: check_para.yml

- name: 检查目标服务器的Docker信息
  include_tasks: check_docker.yml

- name: 复制Web应用Nginx配置文件到目标服务器
  include_tasks: send_files.yml 
  with_items:
    - "{{ web_app.split(',') }}"
  loop_control:
    loop_var: webname

- name: 创建目标服务器Web前端Nginx容器
  include_tasks: build_container.yml
  with_items:
    - "{{ web_app.split(',') }}"
  loop_control:
    loop_var: webname
 
