---
- name: 测试环境添加主机名称解析
  template:
    src: domain_name_resolution/hosts.j2
    dest: "{{ host_dns_file }}"
  when: env == "test" 
    
- name: 测试环境替换域名DNS配置文件
  template: 
    src: domain_name_resolution/resolv.conf.j2
    dest: "{{ resolv_dns_file }}"
  when: env == "test"

- name: 生产环境添加域名解析
  template:
    src: domain_name_resolution/hosts.j2  
    dest: "{{ host_dns_file }}"
  when: env == "prod"
